language: go
sudo: false

go:
  - 1.11.x
  - tip

script:
  - CGO_ENABLED=0

env:
  - CODECOV_TOKEN="5838cf8b-706e-4210-bcfc-36ff3d137666"

matrix:
  allow_failures:
    - go: tip

before_install:
  - go get -v github.com/golang/lint/golint

install:
  - export PATH=$GOPATH/bin:./_output/tools/etcd/bin:$PATH
  - export GO111MODULE=on