language: go
sudo: false

go:
  - 1.11.x
  - tip

env:
  - CODECOV_TOKEN="5838cf8b-706e-4210-bcfc-36ff3d137666"

matrix:
  allow_failures:
    - go: tip

before_install:
  - go get -v github.com/golang/lint/golint
  - go get -t -v ./...
  - golint

script:
  - CGO_ENABLED=0
  - go test -race -v ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

install:
  - export PATH=$GOPATH/bin:./_output/tools/etcd/bin:$PATH
  - export GO111MODULE=on

branches:
  except:
    - /^*-v[0-9]/